package com.asusoftware.TermoPro.user_time_off.model;

public enum TimeOffType {
    CONCEDIU,
    INVOIRE,
    CONCEDIU_MEDICAL,
    CONCEDIU_DE_ODIH,
    CONCEDIU_DE_CRESTERE_A_COPILULUI,
    CONCEDIU_DE_RISIPIRE_A_COPILULUI,
    CONCEDIU_DE_URGENTA,
    CONCEDIU_DE_MATERNITATE,
    CONCEDIU_DE_PATERNITATE,
    CONCEDIU_DE_ADOPTIE,
    CONCEDIU_DE_FAMILIE,
    CONCEDIU_DE_SOMAJ,
    CONCEDIU_DE_VACANTA
}
